{% set version = "1.38.1" %}

package:
  name: geocoder
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/geocoder/geocoder-{{ version }}.tar.gz
  sha256: c9925374c961577d0aee403b09e6f8ea1971d913f011f00ca70c76beaf7a77e7

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - geocode = geocoder.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - ratelim
    - click
    - six
    - future

test:
  requires:
    - python {{ python_min }}
  imports:
    - geocoder
  commands:
    - geocode --help

about:
  home: https://github.com/DenisCarriere/geocoder
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Geocoder is a simple and consistent geocoding library'

extra:
  recipe-maintainers:
    - ocefpaf
